apiVersion: v1
kind: Pod
metadata:
  name: store-db
  namespace: postgresqldev
  labels:
        app: store-db
spec:
  containers:
    - name: store-db
      image: <REGISTRY_NAME>.azurecr.io/store-db:latest
      volumeMounts:
        - mountPath: "/var/lib/postgresql/"
          name: postgresql-data
      imagePullPolicy: IfNotPresent
      ports:
      - containerPort: 5432
        name: postgresql
      env:
      - name: POSTGRES_DB
        value: "contosostore"
      - name: POSTGRES_PASSWORD
        value: "Solliance123"
  imagePullSecrets:
    - name: acr-secret
  volumes:
    - name: postgresql-data
      persistentVolumeClaim:
        claimName: postgresql-data