apiVersion: v1
kind: Pod
metadata:
  name: store-web
  namespace: postgresqldev
  labels:
        app: store-web
spec:
  containers:
    - name: store-web
      image: <REGISTRY_NAME>.azurecr.io/store-web:latest
      imagePullPolicy: IfNotPresent
      ports:
      - containerPort: 80
        name: http
      - containerPort: 443
        name: https
      env:
      - name: APP_URL
        value: ""
      - name: DB_DATABASE
        value: "contosostore"
      - name: DB_USERNAME
        value: "postgres"
      - name: DB_PASSWORD
        value: "Solliance123"
      - name: DB_HOST
        value: "store-db-svc"
  imagePullSecrets:
    - name: acr-secret