FROM postgres:16.1
#RUN chown -R postgresql:root /var/lib/postgresql/data

ADD artifacts/data.sql /etc/postgresql/data.sql

ENV POSTGRES_DB contosostore

RUN cp /etc/postgresql/data.sql /docker-entrypoint-initdb.d

EXPOSE 5432 22