version: '3.8'
services:
  web:
    image: store-web
    environment:
      - DB_DATABASE=contosostore
      - DB_USERNAME=postgres
      - DB_PASSWORD=Solliance123
      - DB_HOST=db
      - DB_PORT=5432
    ports:
      - "8080:80" 
  db:
    image: store-db
    restart: always
    environment:
      - PGADMIN_DEFAULT_PASSWORD=Solliance123
      - PostgreSQL_DATABASE=contosostore
    volumes:
      - "db-volume:/var/lib/postgresql"
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    ports:
        - '8081:80'
    restart: always
    environment:
        PMA_HOST: db
    depends_on:
        - db
volumes:
  db-volume:
    external: false